### ISSUE TITLE
Dev Environment for code contributors

### ISSUE THREAD

**Issue by isocroft** [onyekaa/nlist#10]
@onyekaa judging from the fact that this is an open-source project (correct me if i'm wrong) i think it will be nice to give more details about the **nlist project** on the README.md file so code contributors who are interested can follow and have a dev installation (e.g Heroku or Cloud9) to work with and contribute.

Thanks and thumbs up on this project!!

**Comment by onyekaa** [comment]
This isn't an open source, sorry for the confusion
